my_site/urls.py
from django.contrib import admin
import xadmin
from django.urls import path, include
from users import views
from .views import download_file, delete_file, upload_file
                    
urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path(r'captcha/', include('captcha.urls')),  # 验证码
    
    #users.view
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update_password/', views.update_password, name='update_password'),

    path('upload/', upload_file, name='upload_file'),
    path('delete/<str:file_path>', delete_file, name='delete_file'),
    path('download/<str:file_path>', download_file, name='download_file'),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('thesis/', include('thesis.urls')),
]

teacher/urls.py
from django.urls import path, include
from . import views
from message.views import send_message
from announcement.views import all_announcement, announcement_detail

urlpatterns = [
    path('', views.teacher_home, name = 'teacher_home' ),
    path('announcement/', all_announcement, name='teacher_announcement'),
    path('announcement/<int:announcement_pk>', announcement_detail, \
                                                name='teacher_ann_detail'),
    path('update_info/', views.update_info, name='teacher_update_info'),

    path('thesis/', views.teacher_thesis, name = 'teacher_thesis'),

    path('thesis/publish', views.publish_thesis, name = 'publish_thesis'),
    path('thesis/<int:thesis_pk>/update', views.update_thesis, name='update_thesis'),
    path('thesis/delete', views.delete_thesis, name='delete_thesis'),


    path('group/', include([
        path('', views.group, name='group'),
        path('files/', views.group_files, name='group_files'),
        path('member', views.student_info, name='student_info'),
        path('aggre_thesis/', views.aggre_thesis, name='aggre_thesis'),
        path('disaggre_thesis/', views.disaggre_thesis, name='disaggre_thesis'),
        ])),

    path('message/', views.latest_message, name='teacher_message'),
    path('message/message_with_student', views.message_with_student, name='message_with_student'),
    path('message/send_message', send_message, name='send_message'),
]

thesis/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:thesis_pk>', views.thesis_detail, name='thesis_detail' ),
]

message/models.py
from django.db import models
from users.models import User


class Message(models.Model):
    content = models.TextField()
    sender = models.ForeignKey(User, on_delete = models.CASCADE,\
                                verbose_name='发送者', related_name='sender')
    receiver = models.ForeignKey(User, on_delete = models.CASCADE,\
                                verbose_name='接收者', related_name='receiver')
    send_time = models.DateTimeField(auto_now_add = True)
    is_read = models.BooleanField(default = False)

    class Meta:
        ordering = ['-send_time']
        verbose_name_plural = '消息'

    def __str__(self):
        return self.content

thesis/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor.fields import RichTextField

class Tag(models.Model):
    name = models.CharField(max_length = 50, verbose_name='标签名')

    def __str__(self):
        return '%s'%self.name

    class Meta:
        verbose_name_plural = '论文标签'

class Thesis(models.Model):
    title = models.CharField(max_length = 255, verbose_name='论文题目')
    content = RichTextField(default='', verbose_name='选题内容')
    pub_date = models.DateField(auto_now_add = True, verbose_name='发布日期')
    publisher = models.ForeignKey('users.User', on_delete = models.DO_NOTHING, verbose_name='发布者')
    is_choiced = models.BooleanField(default = False, verbose_name = '已有学生选择')
    tags = models.ManyToManyField(Tag, verbose_name='选题标签', blank=True)
    need_verify = models.BooleanField(default = False, verbose_name='待审核')
    collection = GenericRelation('student.Collection')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = '论文题目'
        ordering = ['-pub_date']
        unique_together = (('title', 'publisher'))

    def getCollege(self):
        if self.publisher.person == 'student':
            return self.publisher.student.college
        elif self.publisher.person == 'teacher':
            return self.publisher.teacher.college
        else:
            return None
    getCollege.short_description = '学院名称'

class DisagreeThesisReson(models.Model):
    text = models.TextField(verbose_name='理由')
    thesis = models.OneToOneField(Thesis,on_delete=models.CASCADE,verbose_name='论文题目')

teacher/forms.py
from django import forms


class UpdateInfoForm(forms.Form):
    college = forms.CharField(label = '学院', widget=forms.TextInput(attrs={'class':'input-field'}))
    job_title = forms.CharField(label = '职称', widget=forms.TextInput(attrs={'class':'input-field'}))
    phone_number = forms.CharField(label='手机号码', widget=forms.TextInput(attrs={'class':'input-field'}))
    max_number = forms.IntegerField(label='最大指导人数',\
                                    widget=forms.NumberInput(attrs={'class':'input-field'}))
    introduction = forms.CharField(label='简介', required=False,
                                    widget=forms.Textarea(attrs={'class':'form-control'}))
    

    def clean_max_number(self):
        max_number = self.cleaned_data.get('max_number')
        if max_number < 0:
            raise forms.ValidationError('不能小于0')
        else:
            return max_number

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if len(phone_number) != 11:
            raise form.ValidationError('请输入正确的手机号')
        else:
            return phone_number

message/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import JsonResponse

from my_site.utils import sendMessage
from message.models import Message

def send_message(request):
    user = request.user
    if user.is_authenticated:
        receiver_pk = request.POST.get('receiver_pk', None)
        content = request.POST.get('message', None)
        if receiver_pk:
            data = sendMessage(receiver_pk, user, content)
            return JsonResponse(data)
        else:
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        messages.error(request, '请先登录')
        return redirect('/')

teacher/views.py
#django里的
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.db.utils import IntegrityError  #键值重复错误
from django.contrib import messages

#自己写的模型、方法
from announcement.utils import getAnnouncement
from users.models import User
from student.models import Student

from message.models import Message
from thesis.models import Thesis, Tag, DisagreeThesisReson
from thesis.forms import PublishThesisForm, UpdateThesisForm
from my_site.utils import get_public_file, \
                           get_teacher_file, get_student_file
from .forms import UpdateInfoForm


def teacher_home(request):
    user = request.user
    if user.is_authenticated and user.person=='teacher':
        teacher = user.teacher

        no_r_mesg_count = Message.objects.filter(receiver=user, is_read=False).count()
        announcements = getAnnouncement(user)
        no_r_ann_count = announcements.count() - user.read_announcement.count()
        if user.no_r_ann_count != no_r_ann_count or user.no_r_message_count != no_r_mesg_count:
            user.no_r_ann_count = no_r_ann_count
            user.no_r_message_count = no_r_mesg_count
            user.save()

        #获取需要审核的论文题目
        need_verify_thesis = Thesis.objects.filter(publisher__person = 'student', \
                                        publisher__student__teacher = user.teacher,\
                                        need_verify=True)

        context = {}
        context['teacher'] = teacher
        context['need_verify_thesis'] = need_verify_thesis
        
        return render(request, 'teacher/teacher_home.html', context)
    else:
        messages.error(request, '请先登录')
        return redirect('/')

def group(request):
    user = request.user
    if user.is_authenticated and user.person == 'teacher':
        if request.method == 'POST':
            message_content = request.POST.get('group_ann') #获取消息内容
            if message_content.strip():
                students = user.teacher.student_set.all()
                for student in students:
                    Message.objects.create(receiver = student.user, sender = user,\
                                            content = message_content)
                    messages.success(request, '发送成功！')
            else:
                messages.error(request, '不能为空！')
            return redirect(request.META.get('HTTP_REFERER','/'))
        else:
            teacher = user.teacher
            students = teacher.student_set.all()

            context = {}
            context['students'] = students
            return render(request, 'teacher/group_member.html' ,context)
    else:
        messages.error(request, '请先登录')
        return redirect('/')

def group_files(request):
    user = request.user
    if user.is_authenticated and user.person == 'teacher':
        students_dict = {}
        teacher = user.teacher
        students = teacher.student_set.all()

        for student in students:
            student_file_dict = get_student_file(student)
            students_dict[student] = student_file_dict
        #获取公共文件文件夹下的所有文件
        public_files_dict = get_public_file(user.person)
        teacher_files_dict = get_teacher_file(teacher)


        context = {}
        context['students'] = students
        context['students_dict'] = students_dict
        context['public_files_dict'] = public_files_dict
        context['teacher_files_dict'] = teacher_files_dict

        return render(request, 'teacher/group_file.html' ,context)
    else:
        messages.error(request, '请先登录')
        return redirect('/')

def update_info(request):
    user = request.user
    if user.is_authenticated and user.person=='teacher':
        teacher = user.teacher
        #判断用户是提交修改数据还是进入修改数据页面
        if request.method == 'POST':
            update_info_form = UpdateInfoForm(request.POST)
            if update_info_form.is_valid():
                max_number = update_info_form.cleaned_data['max_number']
                teacher.college = update_info_form.cleaned_data['college']
                teacher.job_title = update_info_form.cleaned_data['job_title']
                teacher.introduction = update_info_form.cleaned_data['introduction']
                teacher.max_number = max_number
                teacher.phonenumber = update_info_form.cleaned_data['phone_number']
                teacher.rest_number = max_number - teacher.student_set.all().count()
                teacher.save()
                messages.success(request, '修改成功！')
                return redirect(reverse('teacher_home'))

        else:
            #将用户原来的数据提取出来放到初始化UpdateInfoForm表单的数据上
            initial_data={'college':teacher.college,'max_number':teacher.max_number,\
                        'job_title':teacher.job_title,'introduction':teacher.introduction,\
                        'phone_number':teacher.phonenumber}
            update_info_form = UpdateInfoForm(initial = initial_data)
        context = {}
        context['update_info_form'] = update_info_form
        return render(request, 'teacher/update_info.html', context)
    else:
        messages.error(request, '请先登录')
        return redirect('/')

def teacher_thesis(request):
    user = request.user
    if user.is_authenticated and user.person=='teacher':
        all_theses = Thesis.objects.filter(publisher = user)
        need_verify_theses = Thesis.objects.filter(publisher__person = 'student', \
                                publisher__student__teacher = user.teacher,need_verify=True)

        context = {}
        context['theses'] = all_theses
        context['is_choiced_theses'] = all_theses.filter(is_choiced=True)
        context['no_choiced_theses'] = all_theses.filter(is_choiced=False)
        context['need_verify_theses'] = need_verify_theses
        return render(request, 'teacher/teacher_thesis.html', context)
    else:
        messages.error(request, '请先登录')
        return redirect('/')

def publish_thesis(request):
    user = request.user
    if user.is_authenticated and user.person=='teacher':
        if request.method == 'POST':
            publish_thesis_form = PublishThesisForm(request.POST)
            if publish_thesis_form.is_valid():
                title = publish_thesis_form.cleaned_data['title']
                content = publish_thesis_form.cleaned_data['content']
                tags = publish_thesis_form.cleaned_data['tag'].split()
                try:
                    thesis = Thesis.objects.create(title = title, content = content, publisher =user)
                    for tag in tags:
                        tag_obj, is_create = Tag.objects.get_or_create(name = tag)
                        thesis.tags.add(tag_obj)
                    messages.success(request, '发布选题成功！')
                    return redirect(request.GET.get('from', '/'))    #发布成功，跳转到原来的页面
                except IntegrityError:
                    publish_thesis_form.add_error(None, '不能重复创建同一论文题目')
        else:
            publish_thesis_form = PublishThesisForm()

        context = {}
        context['thesis_form'] = publish_thesis_form
        context['panel_head'] = '发布论文题目'
        context['submit_value'] = '发布'
        return render(request, 'teacher/publish_thesis.html', context)
    else:
        redirect('/')

#修改论文题目信息
def update_thesis(request, thesis_pk):
    user = request.user
    if user.is_authenticated and user.person=='teacher':
        thesis = Thesis.objects.get(pk = thesis_pk)
        initial = {'title':thesis.title, 'content':thesis.content}
        if request.method == 'POST':
            update_thesis_form = UpdateThesisForm(request.POST, initial=initial)
            if update_thesis_form.is_valid():
                if update_thesis_form.has_changed():
                    title = update_thesis_form.cleaned_data['title']
                    content = update_thesis_form.cleaned_data['content']
                    try:
                        thesis.title = title
                        thesis.content = content
                        thesis.save()
                        messages.success(request, '修改成功')
                        return redirect(request.GET.get('from', '/'))
                    except IntegrityError:
                        update_thesis_form.add_error(None, '不能重复创建同一论文题目')
                else:
                    return redirect(request.GET.get('from', '/'))
        else:
            update_thesis_form = UpdateThesisForm(initial=initial)
        context = {}
        context['thesis_form'] = update_thesis_form
        context['panel_head'] = '修改论文题目信息'
        context['submit_value'] = '修改'
        return render(request, 'teacher/publish_thesis.html', context)
    else:
        return redirect('/')

def delete_thesis(request):
    user = request.user
    if user.is_authenticated and user.person=='teacher':
        try:
            thesis_title = request.GET.get('thesis_title', None)
            if thesis_title:
                thesis = Thesis.objects.get(title = thesis_title, publisher=user)
                if not thesis.is_choiced:
                    thesis.delete()
                    messages.success(request,'删除成功！')
                else:
                    messages.error(request,'该选题已有人选择')
            return redirect(reverse('teacher_thesis'))
        except ObjectDoesNotExist:
            messages.error(request, '未找到该选题！')
        return redirect(request.META.get('HTTP_REFERER', reverse('teacher_thesis')))
    else:
        return redirect('/')

def student_info(request):
    user = request.user
    if user.is_authenticated and user.person == 'teacher':
        context = {}
        student_name = request.GET.get('student_name')
        try:
            student = Student.objects.get(name = student_name, teacher=user.teacher)
            thesis = student.thesis
            if not thesis:
                student_pub_thesis = Thesis.objects.filter(publisher=student.user, is_choiced=True)

teacher/templates/teacher/announcement_detail.html
{% extends 'teacher/teacher_ann.html' %}

{% block title %}公告{% endblock %}

{% block content_header %}公告信息{% endblock %}

{% block content %}
    <p>
        发布者：
            {% if announcement.sender.is_superuser %}
                管理员
            {% else %}
                {{ announcement.sender.name }}管理员
            {% endif %}
        时间：{{ announcement.pub_time }}
    </p>
    <p>{{ announcement.text }}</p>
{% endblock %}

teacher/templates/teacher/group_file.html
{% extends 'teacher/teacher_base.html' %}
{% load staticfiles %}

{% block title %} 所有文件 {% endblock %}
{% block header_extends %}
    <script src="{% static 'extends_js.js' %}"></script>
    <script>
        window.onload = function(){
            var form = document.getElementsByTagName('form')[0];
            var upload_btn = document.getElementById('upload_btn');
            upload_btn.onclick = upload_file;

        }
    </script>
{% endblock %}

{% block content_header %}所有文件{% endblock %}

{% block group_active %}active{% endblock %}
{% block files_active %}active{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                管理员文件
            </div>
            <div class="panel-body">
                 {% for file, file_path in public_files_dict.items %}
                    <a href="{% url 'download_file' file_path %}">{{ file }}</a>
                {% empty %}
                    <p>暂无文件</p>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                我上传的文件
            </div>
            <div class="panel-body">
                {% for file, file_path in teacher_files_dict.items %}
                <a href="{% url 'download_file' file_path %}">
                    {{ file }}
                </a>
                <a href="{% url 'delete_file' file_path %}" 
                class='btn btn-danger'>删除文件</a> 
                <br>
                {% empty %}
                    <p>暂未上传文件</p>
                {% endfor %}
                <form action="{% url 'upload_file' %}" method="POST" 
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- enctype="multipart/form-data" 表示不对字符进行编码 -->
                    <input type="file" name='myfile' id='uploadFile'>
                    <br>
                    <button id='upload_btn' class='btn btn-primary'>
                        上传文件
                    </button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                学生上传的文件
            </div>
            <div class="panel-body">
                {% for student, student_files_dict in students_dict.items %}
                    <h4>{{ student }}</h4>
                    {% for file, file_path in student_files_dict.items %}
                        <a href="{% url 'download_file' file_path %}">{{ file }}</a>
                    {% empty %}
                        <p>暂无文件</p>
                    {% endfor %}
                {% empty %}
                    <p>暂无学生</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div id="hidebg">
    <div id="show-upload-info">
        <div class="show-info"><h2>文件上传中</h2></div>
    </div>
</div>


{% endblock %}

teacher/templates/teacher/group_member.html
{% extends 'teacher/teacher_base.html' %}
{% load staticfiles %}


{% block title %} 我的小组 {% endblock %}
{% block header_extends %}
    <script src="{% static 'extends_jquery.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('#pub_ann').on('click', pub_ann);
        });
    </script>
{% endblock %}


{% block content_header %}我的小组{% endblock %}

{% block group_active %}active{% endblock %}
{% block member_active %}active{% endblock %}

{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>小组成员</h4>
    </div>
    <div class="panel-body">
        {% for student in students %}
            <h3>
                <a href="{% url 'student_info' %}?student_name={{student.name}}">
                    {{ student.name }}
                </a>
            </h3>
            {% if student.thesis %}
                他的选题：<a href="{% url 'thesis_detail' student.thesis.pk %}">
                    {{ student.thesis.title }}
                </a>
            {% elif student.user.thesis_set.all %}
                <span class="text-danger">他提交的待审核的选题：</span>
                <a href="{% url 'thesis_detail' student.user.thesis_set.first.pk %}">
                    {{ student.user.thesis_set.first.title }}
                </a>
            {% else %}
                <h4>暂未选择题目</h4>
            {% endif %}
        {% empty %}
            <h3>暂无学生</h3>
        {% endfor %}
        {% if students %}
        <div class="teacher-pub-ann">
            <button id='showPubForm' class='btn btn-primary'>
                发布公告
            </button>
        </div>
        <div class='teacher-pub-form' id='pubForm'>
            <form action="" method="POST">
                {% csrf_token %}
                <label for="group_ann">请输入内容</label> <br />
                <textarea class='teacher-pub-text' id='group_ann' name='group_ann'
                        placeholder='请输入内容'></textarea> <br />
                <button class='btn btn-primary pull-right' id='pub_ann'>发布</button>
            </form>
            <button class='btn btn-danger mar-right' onclick='hid_div()'>
                取消
            </button>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %} 

teacher/templates/teacher/message.html
{% extends 'teacher/teacher_base.html' %}

{% block content_header %}全部消息{% endblock %}

{% block message_active %}active{% endblock %}
{% block no_r_message_active %} active {% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-6">
      <div class="list-group">
        {% for student, latest_message in latest_message_dict.items %}
          <!-- 显示消息发送者和时间  -->
          <a href="{% url 'message_with_student' %}?student_pk={{ student.pk }}" 
                    class="list-group-item">
            <h4 class="list-group-item-heading">
              <span>
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                  {{ student.name }}
                  <!-- 显示发送者的名字 -->
              </span>
              
              <span class='pull-right'>
                <i class="fa fa-fw fa-clock-o" aria-hidden="true"></i>
                  {{ latest_message.send_time|date:'m-d i:s' }}
              </span>
            </h4>
            <p class="list-group-item-text">
              {{ latest_message.content|truncatechars:30 }}
            </p>
            </a>
          {% empty %}
            <div class="center">
                <i class="fa fa-commenting-o fa-5x" aria-hidden="true"></i>
                <p>暂无未读公告</p>
            </div>
          {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

teacher/templates/teacher/publish_thesis.html
{% extends 'teacher/teacher_base.html' %}
{% load staticfiles %}


{% block title %}发布选题{% endblock %}
{% block info_active %}{% endblock %}
{% block my_thesis_active %}active{% endblock %}

{% block content_header %}
    {{ panel_head }}
{% endblock %}

{% block content %}
    <form action="" method='POST'>
        <h3 class="text-danger">{{ thesis_form.non_field_errors }}</h3>
        {% csrf_token %}
        {% for field in thesis_form %}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label> <br>
            {{ field }}
            {% if field.name == 'tag' %}
                <span class='text-danger'>如果想给论文题目增加多个标签，可以使用空格分隔标签</span>
            {% endif %}
            <p class='text-danger'>{{ field.errors.as_text }}</p>
        {% endfor %}
        <input type="submit" value='{{ submit_value }}' class='btn btn-primary pull-right'>
        <a href="javascript:window.history.go(-1)" class="btn btn-danger mar-right">返回</a>
    </form>
{% endblock %}


{% block script_extends %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

teacher/templates/teacher/send_message.html
{% extends 'teacher/message.html' %}
{% load staticfiles %}

{% block title %}发消息{% endblock %}

{% block content_header %}发送消息{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary direct-chat direct-chat-primary" >
                <div class="box-header with-border pull-center">   
                  <!-- box-header -->
                  <h3 class="box-title">与{{ student.name }}的对话</h3>  <!--人名 -->
                </div>   <!-- /.box-header -->
          
            <div class="box-body">    <!-- 这里显示消息内容 开始 -->
              <div class="direct-chat-messages" id='message_box'>
                <!-- 对方发送的消息 -->
                {% for message in both_messages %}
                  {% if message.sender.person == 'student' %}    <!-- 判断消息的发送者是否为学生 -->
                      <div class="direct-chat-msg">    <!-- 显示消息的信息：发送者，时间,开始 -->
                          <div class="direct-chat-info clearfix">
                              <span class="direct-chat-name pull-left">{{ student.name }}</span>
                              <span class="direct-chat-timestamp pull-right">
                                {{ message.send_time|date:'m-d H:i' }}
                              </span>
                          </div>

                          <!-- class为自定义，显示消息内容 -->
                          <div class="chat-text">{{ message.content }}</div>  
                      </div>   <!-- 显示消息的信息：发送者，时间 结束 -->

                  {% else %}   <!-- 如果消息的发送者为老师，则在右边 -->
                      <div class="direct-chat-msg right">
                          <div class="direct-chat-info clearfix">
                              <span class="direct-chat-name pull-right">我</span>
                              <span class="direct-chat-timestamp pull-left">
                                {{ message.send_time|date:'m-d H:i' }}
                              </span>
                          </div>
                        <div class="chat-text-right">
                          {{ message.content }}
                        </div>
                      </div>
                    {% endif %}
                  {% endfor %}
                  </div>
              </div>  <!-- 消息的内容 结束 -->

              <div class="box-footer">
                  <form action="{% url 'send_message' %}" method="post" id='send_message_form'>
                      {% csrf_token %}
                      <input type="hidden" name='receiver_pk' value='{{ student.user.pk }}'>
                      <div class="input-group">
                          <input type="text" name="message" id='message_input' class="form-control">
                          <span class="input-group-btn">
                              <button type="submit" class="btn btn-primary btn-flat">发送</button>
                          </span>
                      </div>
                      <p class="text-danger" id='message_error'></p>
                  </form>
              </div>
          </div>
      </div>
  </div>
  <script>
    function ScrollToBottom(){
      var showTxt = document.getElementById("message_box");
      showTxt.scrollTop = showTxt.scrollHeight;
    }
    ScrollToBottom()
  </script>

{% endblock %}

{% block script_extends %}
  <script>
    $('#send_message_form').submit(function(){
    $.ajax({
        url:"{% url 'send_message' %}",
        type: 'POST',
        data: $(this).serialize(),
        cache: false,
        success: function(data){
          var showTxt = document.getElementById("message_box");
          $('#message_error').text('');
          console.log(data);
          if (data['status'] == 'SUCCESS'){
            //插入数据
            var message_html = '<div class="direct-chat-msg right">' +
                          '<div class="direct-chat-info clearfix">' +
                          '<span class="direct-chat-name pull-right">我</span>' +
                          '<span class="direct-chat-timestamp pull-left">' +
                          data['send_time'] + '</span></div>' +
                    '<div class="chat-text-right">'+ data['message'] +'</div></div>';

            $('#message_box').append(message_html)
            $('#message_input').val('');
            showTxt.scrollTop = showTxt.scrollHeight;
          }
          else{
          //显示错误信息
            $('#message_error').text(data['message_error']);
          }
        },
        error: function(xhr){
          console.log(xhr);
        },
        });
        return false;
    })
  </script>
{% endblock %}

teacher/templates/teacher/teacher_ann.html
{% extends 'teacher/teacher_base.html' %}

{% block title %}所有公告{% endblock %}

{% block content_header %}所有公告{% endblock %}

{% block message_active %}active{% endblock %}
{% block all_ann_active %}active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="list-group">
                {% for announcement in announcements %}
                  <a href="{% url 'teacher_ann_detail' announcement.pk %}" 
                    class="list-group-item">
                      <h4 class="list-group-item-heading">
                        <span>
                          <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                          {%  if announcement.sender.is_superuser%}
                            管理员
                          {% else %}
                            {{ announcement.sender.name }}管理员 
                          {% endif %} 
                            <!-- 显示发送者的名字 -->
                        </span>
                        
                        <span class='pull-right'>
                          <i class="fa fa-clock-o" aria-hidden="true"></i>
                            {{ announcement.pub_time|date:'m-d i:s' }}
                        </span>
                      </h4>
                      <p class="list-group-item-text">
                        {{ announcement.text|truncatechars:30 }}
                      </p>
                  </a>
                {% empty %}
                    <div class="center">
                        <i class="fa fa-bell fa-5x" aria-hidden="true"></i>
                        <p>暂无未读公告</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}